/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : TFC_LEDS.c
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : BitsIO
**     Version     : Component 02.108, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-04-18, 11:14, # CodeGen: 60
**     Abstract    :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings    :
**         Port name                   : PTB
**
**         Bit mask of the port        : 0x0F00
**         Number of bits/pins         : 4
**         Single bit numbers          : 0 to 3
**         Values range                : 0 to 15
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 9 = 009H
**         Initial pull option         : off
**
**         Port data register          : GPIOB_PDOR [0x400FF040]
**         Port control register       : GPIOB_PDDR [0x400FF054]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    47   |   PTB8/EXTRG_IN
**                    1      |    48   |   PTB9
**                    2      |    49   |   PTB10/SPI1_PCS0
**                    3      |    50   |   PTB11/SPI1_SCK
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents    :
**         GetDir - bool TFC_LEDS_GetDir(void);
**         GetVal - byte TFC_LEDS_GetVal(void);
**         PutVal - void TFC_LEDS_PutVal(byte Val);
**         GetBit - bool TFC_LEDS_GetBit(byte Bit);
**         PutBit - void TFC_LEDS_PutBit(byte Bit, bool Val);
**         SetBit - void TFC_LEDS_SetBit(byte Bit);
**         ClrBit - void TFC_LEDS_ClrBit(byte Bit);
**         NegBit - void TFC_LEDS_NegBit(byte Bit);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file TFC_LEDS.c
** @version 01.00
** @brief
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
*/         
/*!
**  @addtogroup TFC_LEDS_module TFC_LEDS module documentation
**  @{
*/         

/* MODULE TFC_LEDS. */

#include "TFC_LEDS.h"

#ifdef __cplusplus
extern "C" {
#endif 

/*
** ===================================================================
**     Method      :  TFC_LEDS_GetDir (component BitsIO)
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always TRUE, Output only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool TFC_LEDS_GetDir(void)

**  This method is implemented as a macro. See TFC_LEDS.h file.  **
*/

/*
** ===================================================================
**     Method      :  TFC_LEDS_GetVal (component BitsIO)
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 15)
** ===================================================================
*/
/*
byte TFC_LEDS_GetVal(void)

**  This method is implemented as a macro. See TFC_LEDS.h file.  **
*/

/*
** ===================================================================
**     Method      :  TFC_LEDS_PutVal (component BitsIO)
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 15)
**     Returns     : Nothing
** ===================================================================
*/
/*
void TFC_LEDS_PutVal(byte Val)

**  This method is implemented as a macro. See TFC_LEDS.h file.  **
*/

/*
** ===================================================================
**     Method      :  TFC_LEDS_GetBit (component BitsIO)
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 3)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool TFC_LEDS_GetBit(byte Bit)
{
  bool BitVal;

  (void)BitsIoLdd1_GetBit(BitsIoLdd1_DeviceData, Bit, &BitVal);
  return (BitVal);
}

/*
** ===================================================================
**     Method      :  TFC_LEDS_PutBit (component BitsIO)
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 3)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
/*
void TFC_LEDS_PutBit(byte Bit, bool Val)

**  This method is implemented as a macro. See TFC_LEDS.h file.  **
*/

/*
** ===================================================================
**     Method      :  TFC_LEDS_SetBit (component BitsIO)
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
/*
void TFC_LEDS_SetBit(byte Bit)

**  This method is implemented as a macro. See TFC_LEDS.h file.  **
*/

/*
** ===================================================================
**     Method      :  TFC_LEDS_ClrBit (component BitsIO)
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
/*
void TFC_LEDS_ClrBit(byte Bit)

**  This method is implemented as a macro. See TFC_LEDS.h file.  **
*/

/*
** ===================================================================
**     Method      :  TFC_LEDS_NegBit (component BitsIO)
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
/*
void TFC_LEDS_NegBit(byte Bit)

**  This method is implemented as a macro. See TFC_LEDS.h file.  **
*/

/* END TFC_LEDS. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.06]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
